### ISSUE TITLE
upstreaming your work

### ISSUE THREAD

**Issue by okias** [corellium/projectsandcastle#26]
Hello,

first thank you for your effort to extended Linux kernel support with iOS devices.

Second - do you plan upstream your effort into mainline Linux kernel?
If you do, 
 * please read https://kernelnewbies.org/FirstKernelPatch , you'll be probably most interested in part sending patches.
 * try not push big commits with multiple changes and commit driver by driver and change by change in order as they depend on 
 * while you edit not yet merged functionality, you can create new commit and squash them on rebase before sending to ML (mailing list)
 * when you have to make some "hack" to make it work, which breaks something else (e.g. other device or driver), mark the commit where you doing this stuff with something like "HACK: " or "xxx: "
 * [commit naming](https://gist.github.com/matthewhudson/1475276) and driver changes should be prefixed

**Comment by cmwdotme** [comment]
Currently there are no plans on upstreaming due to incompatibilities in how the existing drivers are implemented.

**Comment by okias** [comment]
Linux kernel it's really variable and if you wanted, you could (together with linux kernel community) get platform code back into kernel and make it work for everyone properly.

Since you really don't plan put energy into upstreaming your work, my opinion is that this is only PR stunt, since it'll have no real use in the end.

I wish you consider give something back to community from you got rest of Linux sources that allowed you make it working.

**Comment by Mis012** [comment]
> Currently there are no plans on upstreaming due to incompatibilities in how the existing drivers are implemented.

I'm not sure I understand what exactly you mean by this. Is it that you don't write the drivers with the "do things right" mindset, or is there some issue on the linux side of things? Also, in case you are talking about android-specific patches, those are really a separate issue, and google makes sure to rebase them to my knowledge, so really all that should be upstreamed are hardware drivers (especially SoC / pmic drivers). As long as the device boots to working usb communication on plain mainline, we'll be happy, that's really the worst part of platform upbring and it would be a shame to lose that progress.

**Comment by cunidev** [comment]
I think you are underestimating the importance of this issue. Upstreaming the work, or at least working with that as a possible final goal, would bring this project from what is essentially a toy project to having the first proprietary Apple SoC entirely supported by Linux.

**Comment by cunidev** [comment]
In other words, I (maybe "we") kindly ask you to reopen it at least as a reference for a longer-term goal.

**Comment by Mis012** [comment]
I think it's important to split the commits in order to split the issue into smaller parts, which can be handled

**Comment by cmwdotme** [comment]
"Since you really don't plan put energy into upstreaming your work, my opinion is that this is only PR stunt, since it'll have no real use in the end."

> Linux kernel is really flexible and if you wanted, you could (together with linux kernel community) get platform code back into kernel and make it work for everyone properly.
> 
> Since you really don't plan put energy into upstreaming your work, my opinion is that this is only PR stunt, since it'll have no real use in the end.
> 
> I wish you consider give something back to community from you got rest of Linux sources that allowed you make it working.

It's exactly this kind of comment that turns us off upstreaming the work. We put a lot of effort into something and offer it free and open source and all you can do is call into question our motivations for it? I'm sorry I missed the part where you explained why you couldn't upstream it yourself? It's open source... Have at it.

**Comment by cmwdotme** [comment]
> > Currently there are no plans on upstreaming due to incompatibilities in how the existing drivers are implemented.
> 
> I'm not sure I understand what exactly you mean by this. Is it that you don't write the drivers with the "do things right" mindset, or is there some issue on the linux side of things? Also, in case you are talking about android-specific patches, those are really a separate issue, and google makes sure to rebase them to my knowledge, so really all that should be upstreamed are hardware drivers (especially SoC / pmic drivers). As long as the device boots to working usb communication on plain mainline, we'll be happy, that's really the worst part of platform upbring and it would be a shame to lose that progress.


The Hx chips are unlike any other AArch64 SoC in a number of ways. A few examples: the use of FIQs, using two different custom IOMMUs for the same device at the same time (one of which does not fit in the normal DMA mapping / IOMMU model), unusual one-off bus arrangements where a single device uses multiple buses, alignment restrictions on entry points. (There's more.)

Adding this required breaking a number of assumptions in the kernel, and also violating some abstractions in the driver model. Upstreaming this sort of change is harder than adding a new serial port driver (or whatever you're used to), and would require extensive testing on other AArch64 devices (which are not the focus of this project) to make sure we don't break them. It's more important to not break people's existing hardware than to add new stuff.

As the project progresses, those problems will get worse. The architecture of Hx chips becomes more idiosyncratic as the product line matures.

Additionally, our kernel includes Android patches, which I hope you know are not upstreamed, as well as the equally non-upstreamed APFS. All of this is readily apparent when you actually look at the sources, as you prepare to upstream them yourself.

Finally, upstreaming is not required for a project to be part of the Open Source community. Unlike many handset vendors, we're making this available under the GPL to anyone who is curious or wants to help.

**Comment by Mis012** [comment]
Android patches are not an issue imho, since they are commonly applied separately to mainline or near-mainline kernels, and are not nessary for "normal" linux (which I saw you offering as well iirc).

It is my understanding that SoC support is complex, and unfortunately it seems that is more so in apple's case. You could probably fork aarch64 in the worst case, but that seems really drastic. It might be a good idea to see what the maintainers think of this situation, so even if you don't necessairly want to do it, you may at least know if it's feasible and come to an agreement on how someone might be able to make it work. After all, you probably know more about the architecture than anyone else who may want to help.

Qualcomm to my understanding does also do crazy stuff (though to a lesser degree), and yet several SoCs of theirs have varying level of support in mainline.

It is indeed not mandatory to upstream your changes, but it is a good practice (hardly anyone besides vendors hard forks linux, and the vendors obviously have very skewed view of device/codebase lifetime)

Also, although I don't assume it's malicious on your part, releasing all your changes in one big commit is looked down upon as well in the  free and open source community, and it makes it harder for someone else to upstream the patches.

Again, not to be mean, but if you are offering people to be the ones who upstream it, it would be a nice gesture to add better documentation and commit names, config option descriptions etc - you're really the only ones who know enough about the platform to do that.
