### ISSUE TITLE
What should we do to support other model?

### ISSUE THREAD

**Issue by Umiiii** [corellium/projectsandcastle#6]
Appreciated for the developer first.
We know that developers doesn't have enough time to support all model, but maybe a Hitchhiker's Guide on how to make a your-idevice-version build helps.

**Comment by Stan-Corellium** [comment]
If a device uses the H9P chip, it's probably mostly a matter of adding support for the WiFi, Bluetooth and some minor peripherals (screen backlight, etc.) in the drivers, then writing a device tree. (Some small changes in Android may be needed to let it know about WiFi / Bluetooth quirks.)

If it's another chip, you'll have to reverse-engineer the hardware and write drivers for missing devices (and adjust ones that need to be maybe more general, like maybe the interrupt controller). You'll have to write a device tree that matches the hardware, which is partially reverse-engineering and partially generally available information. There are usually small but important differences between behavior of custom hardware blocks in different generations of Hx chips.

Then hopefully you can get a console using something like our buildroot ramdisk and bring up touch screen, WiFi and Bluetooth.

Because the incredibly annoying 16k changes in Android are done, this might be close to the end of the work.

Hopefully this gives you a framework for further research.
